version: "3.1"

services:
  mongo:
    container_name: kartingstats_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kartingstat
    ports:
      - 27017:27017
